### ISSUE TITLE
[UPDATE] Readme File Modification

### ISSUE THREAD

**Issue by Mahitej28** [himanshu-03/Python-Data-Structures#1]
I would like to work on this repository by updating the readme file and adding contribution guidelines to it. Kindly assign me this issue under Hacktoberfest.

**Comment by himanshu-03** [comment]
@all-contributors please add @jakebolam for infrastructure, tests and code

**Comment by himanshu-03** [comment]
@all-contributors please add @Mahitej28 for maintainer, documentation and code
