### ISSUE TITLE
add: Least Angle Regression

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#100]
### Describe the algorithm/code

Least Angle Regression (LARS) is an algorithm used in regression for high dimensional data. Please assign this to me under hacktoberfest tag

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by adi271001** [comment]
created pull request and added codes
