### ISSUE TITLE
add: Ridge Regression

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#103]
### Describe the algorithm/code

Ridge Regression  is a variation of Linear Regression. In Linear Regression, it minimizes the Residual Sum of Squares tto fit the training examples perfectly as possible. The cost function is also represented by J.PLease assign this under hacktoberfest tag

### Do you want to work on this feature?

- [ ] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by adi271001** [comment]
created pull request and added codes
