### ISSUE TITLE
Kruskal’s algorithm

### ISSUE THREAD

**Issue by pankajsingh92533** [himanshu-03/Python-Data-Structures#130]
### Describe the algorithm/code

I want to implement Kruskal’s algorithm in graph folder with proper explanation.
Please assign me this issue under Hacktoberfest 2023 tag.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hey @pankajsingh92533 !
The algorithm  you are willing to add is already present in our repo!
