### ISSUE TITLE
add: TimSort Algorithm

### ISSUE THREAD

**Issue by aggarwal-tanushree** [himanshu-03/Python-Data-Structures#132]
### Describe the algorithm/code

Describe the algorithm/code
**TimSort** is a _hybrid sorting algorithm_ that combines the strengths of merge sort and insertion sort. 
It is designed to efficiently sort a wide range of real-world data types.  It maintains the relative order of equal elements in the sorted output.

- **Divide into Runs**: TimSort starts by dividing the input array into small, already sorted subsequences called "runs."

- **Merge Runs**: It then merges these runs together using a combination of merge sort and insertion sort. This merging process optimizes performance, especially for data with pre-existing order.

Please assign this issue to me as part of Hacktoberfest.

Thanks,
Tanushree 

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by aggarwal-tanushree** [comment]
@himanshu-03  kindly assign this issue to me, with hacktober accepted tag

**Comment by himanshu-03** [comment]
Hi @aggarwal-tanushree ! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨
