### ISSUE TITLE
add: Maximum Subarray Sum (Kadane's Algorithm)

### ISSUE THREAD

**Issue by ydvmudit07** [himanshu-03/Python-Data-Structures#143]
### _Hi @himanshu-03 , I'd like to contribute an implementation of Kadane's algorithm for finding maximum subarray sum as a Hacktoberfest issue. This is a common algorithm challenge and would make a great addition to the repository._

_I can provide an efficient python function that handles:_

- Iterating through the array
- Tracking current maximum sum
- Updating max whenever current sum exceeds it
- Returning maximum sum

_This would be a good beginner-friendly algorithm issue for Hacktoberfest. Kindly tag this issue hacktoberfest-accepted and assign it to me so I can start working on it. Let me know if you need any clarification or have feedback on the approach! Looking forward to contributing._

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by ydvmudit07** [comment]
**_Kindly review the issue and assign it to me,_** @himanshu-03

**Comment by ydvmudit07** [comment]
@himanshu-03 , _let me know if you want any clarification with this issue._

**Comment by himanshu-03** [comment]
Hi @ydvmudit07 ! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨
