### ISSUE TITLE
add: Breadth-First Search (BFS)

### ISSUE THREAD

**Issue by ydvmudit07** [himanshu-03/Python-Data-Structures#144]
### _Hi @himanshu-03 , I'd like to contribute an implementation of breadth-first search (BFS) as a Hacktoberfest issue. BFS is a fundamental graph traversal algorithm and would make a great addition._

_I can provide a python function that handles:_

- Validating graph input
- Initializing visited array
- Enqueuing starting node
- Looping through queue to visit and enqueue neighbors
- Tracking nodes visited
- Returning visited list

_This beginner-friendly algorithm issue would be a good Hacktoberfest contribution. Please tag this issue hacktoberfest-accepted and assign it to me so I can start work. Let me know if you need any clarification or have feedback! Looking forward to contributing._

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by ydvmudit07** [comment]
**_Kindly review the issue and assign it to me,_** @himanshu-03

**Comment by ydvmudit07** [comment]
@himanshu-03 , _let me know if you want any clarification with this issue._

**Comment by himanshu-03** [comment]
We already have this implemented!
