### ISSUE TITLE
Request to Add AVL Tree Code

### ISSUE THREAD

**Issue by Swish78** [himanshu-03/Python-Data-Structures#145]
### Describe the algorithm/code

I would like to request the addition of an AVL tree code to this repository. AVL trees are self-balancing binary search trees and are a fundamental data structure in computer science.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @Swish78 !👋🏻
You can start working on this issue! Do let me know if you need any help. ✨
