### ISSUE TITLE
ExponentialSearch:<python sorting algorithm>

### ISSUE THREAD

**Issue by s7917** [himanshu-03/Python-Data-Structures#19]
### Describe the algorithm/code
hi @himanshu-03 
In the sorting algorithms  , exponential search is very efficient technique  with better space and time complexity, 
so i want to contribute for this issue.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Sure thing you can work under this issue!

**Comment by himanshu-03** [comment]
Why are there two PR's linked with the same issue? #18 #17 
It would be great if you can delete one

**Comment by s7917** [comment]
@himanshu-03 
i will close one poll request
it had done by mistake
sorry for that
