### ISSUE TITLE
add: DFS code for graph

### ISSUE THREAD

**Issue by SaRTHaK0909k** [himanshu-03/Python-Data-Structures#23]
### Describe the algorithm/code

please assign me this issue under the tag hacktoberfest :)

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hey @SaRTHaK0909k !!

You can start working on the issue! If you need any  help do let me know

**Comment by Kallind** [comment]
@SaRTHaK0909k do you need code for GBFS or Astar i have some work done o it... i can contribute as a part of hackoctober fest

**Comment by SaRTHaK0909k** [comment]
@Kallind "Yes, I would be interested in your contribution for GBFS or A* search algorithm. Your help is greatly appreciated!" :)

**Comment by Kallind** [comment]
ok perfect sharing the code and creating a pull request

**Comment by Kallind** [comment]
sent the PR @SaRTHaK0909k .
Please review it.
Thank you!
