### ISSUE TITLE
add: Merge Sort Algorithm

### ISSUE THREAD

**Issue by ashishk1331** [himanshu-03/Python-Data-Structures#33]
### Describe the algorithm/code

Merge sort is a highly efficient and stable sorting algorithm that follows the divide-and-conquer approach. It works by repeatedly dividing an unsorted list into two halves until individual elements are isolated, sorts them, and then merges them back together to form a fully sorted list. 

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
You can work on this issue! Let me know if you need any help.
