### ISSUE TITLE
add: Shell Sort algorithm in sort

### ISSUE THREAD

**Issue by stanleyedward** [himanshu-03/Python-Data-Structures#38]
### Describe the algorithm/code

This code will prompt the user to enter a list of numbers separated by spaces, then apply the shell sort algorithm to sort the list, and finally, display the sorted list.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hey @stanleyedward !
You can start working under this issue!
Do let me know if you need any help
