### ISSUE TITLE
add: Fibonacci Searching Algorithm

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [himanshu-03/Python-Data-Structures#41]
### Describe the algorithm/code

I would like to contribute `Fibonacci searching algorithm` under hacktoberfest 2023.
please assign it to me.
/assign

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by Avdhesh-Varshney** [comment]
@himanshu-03 please assign this task to me to contribute under hacktoberfest 2023

**Comment by himanshu-03** [comment]
You csn start working on this issue!
Happy Hacking!

Do let me know if you need any help ✌️
