### ISSUE TITLE
add: adding binary search tree data structure

### ISSUE THREAD

**Issue by sbdkdlalit0112** [himanshu-03/Python-Data-Structures#46]
### Describe the algorithm/code

I will be adding adding binary search tree data structure and performing basic operations like insertion and traversal

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by sbdkdlalit0112** [comment]
@himanshu-03 I am ready to work on this issue

**Comment by himanshu-03** [comment]
Hey @sbdkdlalit0112 !

You can start working on this issue! Happy Hacking ✨
Do let me know if you need any help

**Comment by Sharnabh** [comment]
hey can youi assign me this issue

**Comment by himanshu-03** [comment]
> hey can youi assign me this issue

Hi @Sharnabh !

As you can see this issue is already opened by @sbdkdlalit0112 . Incase he fails to create a PR until today EOD. You can create a new issue for this and I will assign you with the same.

**Comment by sbdkdlalit0112** [comment]
@himanshu-03 I have made a PR.
