### ISSUE TITLE
Duplicates in sorting algorithm files

### ISSUE THREAD

**Issue by AaryaNale** [himanshu-03/Python-Data-Structures#49]
This file is titled as sorting algorithms and contains only radix and merge sort:
![image](https://github.com/himanshu-03/Python-Data-Structures/assets/91911418/38d1d30e-2425-40b0-967f-0b9f3dbf4090)
While in codes/sorting techniques, we already have some of the sorting algorithms present:
![image](https://github.com/himanshu-03/Python-Data-Structures/assets/91911418/806d1a5c-9b64-4220-a97d-fbb3288f34b3)
How about, we make ONE single file for all the sorting algorithms, and find EVERYTHING in one place?

**Comment by AaryaNale** [comment]
I can fix this issue, if relevant, please assign. 
Thanks.

**Comment by himanshu-03** [comment]
Hi @AaryaNale !
Actually the ones in the algorithm folders have the algorithm for data structures while the codes section has the working code.

**Comment by himanshu-03** [comment]
However, your issue is valid I will fix this out 
will be doing some changes in the structure of the repo

**Comment by himanshu-03** [comment]
Thanks for letting me know btw!
