### ISSUE TITLE
add: Insertion Sort

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#52]
### Describe the algorithm/code

Project Description: Insertion Sort is a simple sorting algorithm that builds the final sorted array one element at a time. It takes each element and inserts it into its correct position within the sorted portion of the array.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hello @prateekpr17 ! 👋🏻

Glad to see you so enthusiastic on contrbuting to the repo but I am sorry to say but the algorithm you are pertaining to is already in our repo. 
Try to come up with some ideas which are not currently present in the repo.
