### ISSUE TITLE
add: Shell Sort

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#53]
### Describe the algorithm/code

Project Description: Shell Sort is an efficient and in-place sorting algorithm that is an extension of the Insertion Sort. It breaks the original list into smaller sub-lists and sorts those sub-lists using Insertion Sort. As the algorithm progresses, the sub-lists become increasingly sorted, leading to a fully sorted list.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hello @prateekpr17 ! 👋🏻

Glad to see you so enthusiastic on contrbuting to the repo but I am sorry to say but the algorithm you are pertaining to is already in our repo. 
Try to come up with some ideas which are not currently present in the repo.
