### ISSUE TITLE
add: Prims algorithm for graph 

### ISSUE THREAD

**Issue by Balajithegr8** [himanshu-03/Python-Data-Structures#54]
### Describe the algorithm/code

hey there, i wanted to add prims algorithm for graph.
I will give proper inputs and outputs and installation guide.
pls assign me this under hacktoberfest. :) 

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hey @Balajithegr8 !

You can start working on this issue. Happy Hacking ✨
Do let me know if you need any help
