### ISSUE TITLE
add: Cocktail Shaker Sort 

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#57]
### Describe the algorithm/code

Issue Description : Cocktail Shaker Sort, also known as Bidirectional Bubble Sort, is a variation of the Bubble Sort algorithm. It works by repeatedly sorting the list in both directions, from left to right and then from right to left, which reduces the number of passes required for sorting. Elements "bubble" up and down until the list becomes fully sorted.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hey @prateekpr17 ! 👋🏻

You can start working on this issue. Do let me know if you need any help! ✨
Happy Hacking! 🚀
