### ISSUE TITLE
add: Gnome Sort 

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#58]
### Describe the algorithm/code

Issue Description : Gnome Sort, also known as "Stupid Sort," is a simple sorting algorithm that repeatedly swaps adjacent elements to move them to their correct positions. It's similar to Bubble Sort but has a more naive approach. Gnome Sort is not efficient for large datasets and is primarily used for educational purposes to illustrate basic sorting concepts rather than practical sorting applications.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @prateekpr17 !

Similarly like #57, this issue too seems like just for an education purpose and not very much practical or implementable in real life tasks.
