### ISSUE TITLE
add: Bogo Sort

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#59]
### Describe the algorithm/code

Issue Description : Bogo Sort, sometimes humorously referred to as "Permutation Sort," is a highly inefficient and random sorting algorithm. It operates by randomly shuffling the elements of a list and checking if the list is sorted. If not, it continues to shuffle the elements randomly and recheck. Bogo Sort has no guaranteed time complexity and can take an impractically long time to sort even small lists. It is primarily used as an illustrative example of a deliberately inefficient algorithm and is not suitable for real-world sorting tasks.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hey @prateekpr17 !

If the sorting algorithms are highly inefficient or not used in real life tasks, then I dont think so we should be adding this to our repo.

**Comment by prateekpr17** [comment]
Ok sir
