### ISSUE TITLE
add: Depth-First Search (DFS)

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#60]
### Describe the algorithm/code

Issue Description : Depth-First Search (DFS) is a graph traversal algorithm that explores as deeply as possible along a branch before backtracking. It's used to visit all the nodes in a graph or tree, typically starting from a root node. DFS is often implemented using recursion or a stack data structure and is useful for tasks like finding connected components, topological sorting, and pathfinding.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
I guess we already have this implemented.
Check here: https://github.com/himanshu-03/Python-Data-Structures/tree/main/Graphs

**Comment by prateekpr17** [comment]
Ok sir 
I just see the algorithms present that file 
I don't refer this file 
Thankyou for telling me
