### ISSUE TITLE
add: Breadth-First Search (BFS)

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#61]
### Describe the algorithm/code

Issue Description : Breadth-First Search (BFS) is a graph traversal algorithm that systematically explores all neighbors of a node before moving on to their neighbors. It starts at the root node and progresses level by level, making it useful for tasks like finding the shortest path in unweighted graphs, exploring the connectivity of a graph, and web crawling. BFS is typically implemented using a queue data structure.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
I guess we already have this implemented.
Check here:  https://github.com/himanshu-03/Python-Data-Structures/tree/main/Graphs
