### ISSUE TITLE
add: Jump Search

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#62]
### Describe the algorithm/code

Issue Description : Jump Search is an efficient searching algorithm for ordered lists. It divides the list into smaller blocks and jumps ahead by fixed steps to quickly reach a block that might contain the target value. It then performs a linear search within that block, providing a balance between the efficiency of binary search and the simplicity of linear search. Jump Search is especially useful for large datasets where binary search might be less efficient due to its logarithmic time complexity.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @prateekpr17 !

It seems the issue and the definition you provided is AI generated!

**Comment by prateekpr17** [comment]
Indeed I've used AI services to generate a more formal language for the description. Nothing more. I've already practiced the algorithm in python.

**Comment by himanshu-03** [comment]
Okay you can start working on this issue! ✌️
