### ISSUE TITLE
Add traveling salesman algorithm

### ISSUE THREAD

**Issue by AaryaNale** [himanshu-03/Python-Data-Structures#65]
### Describe the algorithm/code

The Traveling Salesman Problem (TSP) is a classic optimization challenge, where a salesperson seeks the shortest path to visit a set of cities once, returning to the starting point.
I wish to add the code to this algorithm in this repo. 
Please assign me this issue.
Thanks.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hey @AaryaNale ! 👋🏻

You can start working on this issue. Do let me know if you need any help ✨

**Comment by AaryaNale** [comment]
Sure! Thanks.
