### ISSUE TITLE
add: Bellman-Ford Algorithm

### ISSUE THREAD

**Issue by prateekpr17** [himanshu-03/Python-Data-Structures#71]
### Describe the algorithm/code

Issue Description : The Bellman-Ford Algorithm is a single-source, shortest-path algorithm used to find the shortest paths from a source node to all other nodes in a weighted graph, even when the graph contains negative edge weights. It works by iteratively relaxing the edges in the graph, ensuring that it can detect and handle negative weight cycles.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @prateekpr17 !
You can start working on this issue! Do let me know if you need any help.

**Comment by HarshallSonawane** [comment]
Hello @prateekpr17 ,
Can you please assign me this issue
