### ISSUE TITLE
add: new directory `Math`

### ISSUE THREAD

**Issue by kushchoudhary98** [himanshu-03/Python-Data-Structures#72]
## This 'Math' directory will contain all the python implementation of mathematics functions.

I will also add some methods like: Bisection Method and Sieve of Eratosthenes.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by Sharnabh** [comment]
I am willing to implement this feature

**Comment by himanshu-03** [comment]
Sure thing @kushchoudhary98 !
You can create the issues for Bisection Method and Eratosthenes directly. Do create those issues and lmk I will assign them to you.
Closing this now as only adding a new directory wont be a genuine contrbution towards hacktoberfest
