### ISSUE TITLE
Add kruskal's algorithm

### ISSUE THREAD

**Issue by AaryaNale** [himanshu-03/Python-Data-Structures#74]
### Describe the algorithm/code

I want to add the code for Kruskal's algorithm.
Kruskal's algorithm is a minimum spanning tree algorithm that finds the smallest set of edges that connects all vertices in a graph without forming cycles. Adding this to the "Graphs" folder.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @AaryaNale  !
You can start working on this issue! Do let me know if you need any help.
