### ISSUE TITLE
Dynamic Programming (DP)

### ISSUE THREAD

**Issue by pankajsingh92533** [himanshu-03/Python-Data-Structures#77]
### Describe the algorithm/code

i want to add dynamic programming questions .Please assign me this under Hacktoberfest 2023 tag.

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

**Comment by pankajsingh92533** [comment]
i want to add one easy , one medium and one hard level problem with answer.

**Comment by himanshu-03** [comment]
Hello @pankajsingh92533 !

If you have seen my repo, you can see that we arent targetting programming questions but data structures and algorithms.
Closing this issue as not planned
