### ISSUE TITLE
Binary Search code

### ISSUE THREAD

**Issue by shreyashdelmade0744** [himanshu-03/Python-Data-Structures#8]
### Describe the algorithm/code

Hi @himanshu-03 
I would like to add Binary Search code to your repo , 
can you please assign this to me ?

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Sure thing!
You can work on this issue

**Comment by Sharnabh** [comment]
hey I am intrested, can you assign me this project

**Comment by himanshu-03** [comment]
Hi @shreyashdelmade0744 !

Its been a long time and the Binary Search Code is already implemented and merged by someone.
Closing this issue as stale now.
