### ISSUE TITLE
add: Pattern Searching Algorithm, Naive Pattern Searching 

### ISSUE THREAD

**Issue by ConradKash** [himanshu-03/Python-Data-Structures#80]
### Describe the algorithm/code

Naive pattern searching is the simplest method among other pattern-searching algorithms. It checks for all characters of the main string to the pattern. This algorithm is helpful for smaller texts. It does not need any pre-processing phases.
I can find the substring by checking once for the string. It also does not occupy extra space to perform the operation.

The time complexity of Naive Pattern Search method is O(m*n). The m is the size of pattern and n is the size of the main string.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @prateekpr17 !
You can start working on this issue! Do let me know if you need any help.
