### ISSUE TITLE
Trie Data Structure

### ISSUE THREAD

**Issue by statst** [himanshu-03/Python-Data-Structures#81]
### Describe the algorithm/code

A trie, also known as a prefix tree, is a tree-like data structure that is used to store a dynamic set of strings. It is particularly efficient for tasks like searching for strings with a common prefix. Each node in a trie represents a character in a string.

@himanshu-03 Could you please assign me this under hacktoferbest2023

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @statst! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by statst** [comment]
> > Hi @statst! 👋🏻 You can start working on this issue! Do let me know if you need any help. ✨
> 
> Thanks @himanshu-03 added PR. please review. #106

Thanks @himanshu-03 . Updated code
