### ISSUE TITLE
add: Gaussian Mixture Model

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#85]
### Describe the algorithm/code

Gaussian Mixture Model is another clustering algorithm and it is more accurate than k means algorithm please assign this to me under the hacktoberfest tag

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by adi271001** [comment]
pull request has been created
