### ISSUE TITLE
add: BIRCH Algorithm

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#87]
### Describe the algorithm/code

BIRCH algorithm
The Balance Iterative Reducing and Clustering using Hierarchies (BIRCH) algorithm works better on large data sets than the k-means algorithm. It breaks the data into little summaries that are clustered instead of the original data points. The summaries hold as much distribution information about the data points as possible. please assign me this issue with hacktoberfest tag

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨
