### ISSUE TITLE
add: Affinity Propagation ALgorithm

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#88]
### Describe the algorithm/code

This clustering algorithm is completely different from the others in the way that it clusters data. Each data point communicates with all of the other data points to let each other know how similar they are and that starts to reveal the clusters in the data. You don't have to tell this algorithm how many clusters to expect in the initialization parameters. Please assign me this issue with hacktoberfest tag

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by adi271001** [comment]
created pull request and added codes
