### ISSUE TITLE
add: Mean-Shift clustering algorithm

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#89]
### Describe the algorithm/code

This is another algorithm that is particularly useful for handling images and computer vision processing. Mean-shift is similar to the BIRCH algorithm because it also finds clusters without an initial number of clusters being set. This is a hierarchical clustering algorithm, but the downside is that it doesn't scale well when working with large data sets.Please Assign me this issue with hacktoberfest tag.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨
