### ISSUE TITLE
add: OPTICS algorithm

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#90]
### Describe the algorithm/code

OPTICS stands for Ordering Points to Identify the Clustering Structure. It's a density-based algorithm similar to DBSCAN, but it's better because it can find meaningful clusters in data that varies in density. It does this by ordering the data points so that the closest points are neighbors in the ordering. Please assign me this issue under hacktoberfest tag.

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by adi271001** [comment]
created pull request and added codes
