### ISSUE TITLE
add: Agglomerative Hierarchy clustering algorithm

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#91]
### Describe the algorithm/code

This is the most common type of hierarchical clustering algorithm. It's used to group objects in clusters based on how similar they are to each other. This is a form of bottom-up clustering, where each data point is assigned to its own cluster. Then those clusters get joined together. At each iteration, similar clusters are merged until all of the data points are part of one big root cluster.Please assign me this issue under hacktoberfest tag

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by adi271001** [comment]
created pull request and added codes
