### ISSUE TITLE
Tarjan's Algorithm 

### ISSUE THREAD

**Issue by pankajsingh92533** [himanshu-03/Python-Data-Structures#92]
### Describe the algorithm/code

I want to add Tarjan's Algorithm  .
Please assign me this task under Hactoberfest 2023 tag.

### Do you want to work on this feature?

- [x] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @pankajsingh92533 ! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by pankajsingh92533** [comment]
![tarjan](https://github.com/himanshu-03/Python-Data-Structures/assets/125594928/eaad847c-3094-4085-b5c7-0e7bf768211f)
i have written code with proper explanations.
Please review it..

**Comment by himanshu-03** [comment]
Create a PR.
I will check but make sure that the code is accepting dynamic input
