### ISSUE TITLE
add: Simple linear regression under another directory called asregression techniques

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#93]
### Describe the algorithm/code

Linear regression is a statistical method for modeling relationships between a dependent variable with a given set of independent variables. Please assign this to me under hacktober fest tag 

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨
