### ISSUE TITLE
add: Multiple Linear Rgeression

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#94]
### Describe the algorithm/code

Multiple linear regression attempts to model the relationship between two or more features and a response by fitting a linear equation to the observed data. Please assign me this under hacktoberfest tag

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by adi271001** [comment]
created pull request and added codes
