### ISSUE TITLE
add: Bayesian Regression

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#96]
### Describe the algorithm/code

Bayesian regression is a type of linear regression that uses Bayesian statistics to estimate the unknown parameters of a model. It uses Bayes’ theorem to estimate the likelihood of a set of parameters given observed data. The goal of Bayesian regression is to find the best estimate of the parameters of a linear model that describes the relationship between the independent and the dependent variables. Please assign me this issue under Hacktoberfest tag

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨
