### ISSUE TITLE
add: Quantile Regression

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#97]
### Describe the algorithm/code

Quantile regression is simply an extended version of linear regression. Quantile regression constructs a relationship between a group of variables  and quantiles  dependent variables. Please assign me this issue under hacktoberfets tag

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨
