### ISSUE TITLE
add: Stepwise Regression

### ISSUE THREAD

**Issue by adi271001** [himanshu-03/Python-Data-Structures#99]
### Describe the algorithm/code

Stepwise regression is a method of fitting a regression model by iteratively adding or removing variables. It is used to build a model that is accurate and parsimonious, meaning that it has the smallest number of variables that can explain the data. Please assign this under Hacktoberfest to me

### Do you want to work on this feature?

- [X] I am willing to implement this feature.

**Comment by himanshu-03** [comment]
Hi @adi271001! 👋🏻
You can start working on this issue! Do let me know if you need any help. ✨

**Comment by adi271001** [comment]
created pull request and added codes
